sudo: required
services:
  - docker


before_instal:
  - docker build -t ahfaz-ur/docker-react -f Dockerfile.dev .


script:
  - docker run ahfaz-ur/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-439104221182"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key:
    secure: "$AWS_SECRET_KEY"

